### ISSUE TITLE
Timeout to transitvpc S3 bucket from Configurator Fn

### ISSUE THREAD

**Issue by bucklander** [awslabs/aws-transit-vpc#26]
Running into a strange issue with a new transit VPC deployment from a few days ago, but haven't been able to successfully get spokes online. The poller function successfully finds a new spoke VPC tag, creates EC2 VPNs, and drops configuration files into the S3 bucket, however the "configurator" function, upon "Put" trigger, is seemingly unable to successfully retrieve the `transit_vpc_config.txt` settings file, so the CSR devices are never configured. Logs show that it times out trying to retrieve this file, which is odd that it's unable to access it.

Any idea? The only different thing that I've done with this deployment is add 5 other AWS account IDs to the bucket policy per AWS docs Appendix C, but that's it. Never had this issue before with Transit VPC stack deployments.

CloudWatch debug output for the configurator function execution:
```[DEBUG]	2018-06-05T17:30:36.754Z Checking for DNS compatible bucket for: https://s3-us-west-2.amazonaws.com/transitvpc-vpnconfigs3bucket-xxxxxxxxxx/vpnconfigs/transit_vpc_config.txt

[DEBUG]	2018-06-05T17:30:36.754Z URI updated to: https://transitvpc-vpnconfigs3bucket-xxxxxxxxxx.s3-us-west-2.amazonaws.com/vpnconfigs/transit_vpc_config.txt


[DEBUG]	2018-06-05T17:30:36.755Z CanonicalRequest:
GET
/vpnconfigs/transit_vpc_config.txt


[DEBUG]	2018-06-05T17:31:36.726Z ConnectionError received when sending HTTP request.
Traceback (most recent call last):
File "/var/runtime/botocore/endpoint.py", line 222, in _get_response
proxies=self.proxies, timeout=self.timeout)
File "/var/runtime/botocore/vendored/requests/sessions.py", line 573, in send
r = adapter.send(request, **kwargs)
File "/var/runtime/botocore/vendored/requests/adapters.py", line 419, in send
raise ConnectTimeout(e, request=request)
ConnectTimeout: HTTPSConnectionPool(host='transitvpc-vpnconfigs3bucket-xxxxxxxxxx.s3-us-west-2.amazonaws.com', port=443): Max retries exceeded with url: /vpnconfigs/transit_vpc_config.txt (Caused by ConnectTimeoutError(<botocore.awsrequest.AWSHTTPSConnection object at 0x7f328043cc10>, 'Connection to transitvpc-vpnconfigs3bucket-xxxxxxxxxx.s3-us-west-2.amazonaws.com timed out. (connect timeout=60)'))
```

**Comment by bucklander** [comment]
I would just note also that the Lambda outbound SG hasn't been modified in any way, still allows outbound 0.0.0.0/0 443/TCP. It's almost as if there's an issue with DNS resolution for the bucket name.

**Comment by bucklander** [comment]
Disregard. This ended up being an issue with not deploying an s3 endpoint in the route table for lambda access.
